source "https://rubygems.org"

gem "sinatra"
gem "activerecord", require: "active_record"
gem "rake"
gem "pg"
gem "shotgun"
gem "require_all"
gem "sinatra-activerecord", require: "sinatra/activerecord"
gem "bcrypt"
